[package]
name = "leetcode-merge-two-binary-trees"
version = "0.1.0"
authors = ["Akhi Singhania <akhi@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
